### ISSUE TITLE
error running fast_carpenter on batch system (ttH)

### ISSUE THREAD

**Issue by benkrikler** [benkrikler/fast-carpenter-github-test#1]
**Imported from [gitlab issue 1](https://gitlab.cern.ch/fast-hep/public/fast-carpenter/issues/1)**

https://pastebin.com/DbTvmx3Y

**Comment by benkrikler** [comment]
**On 2018-11-13 Benjamin Krikler (bkrikler) wrote:**

Another, probably-related error:
```
Traceback (most recent call last):
  File "/users/bk17414/.local/bin/fast_carpenter", line 11, in <module>
    load_entry_point('fast-carpenter', 'console_scripts', 'fast_carpenter')()
  File "/software/bk17414/CHIP/fast-carpenter/fast_carpenter/__main__.py", line 69, in main
    return process.run(datasets, sequence)
  File "/users/bk17414/.local/lib/python2.7/site-packages/atuproot/atuproot_main.py", line 56, in run
    return self._run(loop)
  File "/users/bk17414/.local/lib/python2.7/site-packages/atuproot/atuproot_main.py", line 116, in _run
    result = loop()
  File "/users/bk17414/.local/lib/python2.7/site-packages/alphatwirl/datasetloop/loop.py", line 30, in __call__
    self.reader.read(dataset)
  File "/users/bk17414/.local/lib/python2.7/site-packages/alphatwirl/datasetloop/reader.py", line 27, in read
    reader.read(dataset)
  File "/users/bk17414/.local/lib/python2.7/site-packages/alphatwirl/loop/EventDatasetReader.py", line 66, in read
    runids = self.eventLoopRunner.run_multiple(eventLoops)
  File "/users/bk17414/.local/lib/python2.7/site-packages/alphatwirl/loop/MPEventLoopRunner.py", line 93, in run_multiple
    return self.communicationChannel.put_multiple(eventLoops)
  File "/users/bk17414/.local/lib/python2.7/site-packages/alphatwirl/concurrently/CommunicationChannel0.py", line 45, in put_multiple
    task_idx = self.put(t)
  File "/users/bk17414/.local/lib/python2.7/site-packages/alphatwirl/concurrently/CommunicationChannel0.py", line 32, in put
    result = task(*args, **kwargs)
  File "/users/bk17414/.local/lib/python2.7/site-packages/alphatwirl/loop/EventLoop.py", line 53, in __call__
    self.reader.event(event)
  File "/users/bk17414/.local/lib/python2.7/site-packages/alphatwirl/loop/ReaderComposite.py", line 43, in event
    if reader.event(event) is False:
  File "/software/bk17414/CHIP/fast-carpenter/fast_carpenter/summary.py", line 74, in event
    data = chunk.tree.pandas.df(self._all_inputs)
  File "/software/bk17414/CHIP/fast-carpenter/fast_carpenter/masked_tree.py", line 24, in df
    df = self._owner.tree.pandas.df(*args, **kwargs)
  File "/software/bk17414/CHIP/fast-carpenter/fast_carpenter/tree_wrapper.py", line 63, in df
    df = self._owner.tree.pandas.df(*args, **kwargs)
  File "/users/bk17414/.local/lib/python2.7/site-packages/uproot/_connect/to_pandas.py", line 46, in df
    return self._tree.arrays(branches=branches, outputtype=pandas.DataFrame, namedecode=namedecode, entrystart=entrystart, entrystop=entrystop, flatten=flatten, flatname=flatname, cache=cache, basketcache=basketcache, keycache=keycache, executor=executor, blocking=blocking)
  File "/software/bk17414/CHIP/fast-carpenter/fast_carpenter/tree_wrapper.py", line 50, in arrays
    return self.tree.old_arrays(*args, **kwargs)
  File "/users/bk17414/.local/lib/python2.7/site-packages/uproot/tree.py", line 476, in arrays
    return wait()
  File "/users/bk17414/.local/lib/python2.7/site-packages/uproot/tree.py", line 460, in wait
    return uproot._connect.to_pandas.futures2df(futures, outputtype, entrystart, entrystop, flatten, flatname)
  File "/users/bk17414/.local/lib/python2.7/site-packages/uproot/_connect/to_pandas.py", line 161, in futures2df
    df[fn] = list(array.flatten())
  File "/users/bk17414/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 3119, in __setitem__
    self._set_item(key, value)
  File "/users/bk17414/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 3194, in _set_item
    value = self._sanitize_column(key, value)
  File "/users/bk17414/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 3391, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)
  File "/users/bk17414/.local/lib/python2.7/site-packages/pandas/core/series.py", line 4001, in _sanitize_index
    raise ValueError('Length of values does not match length of ' 'index')
ValueError: Length of values does not match length of index
```

This only seems to occur for the last block in the tree, so there seems to be some issue with how we divide the tree into blocks and then make use of the block start and stop...

**Comment by benkrikler** [comment]
**On 2018-11-18 Benjamin Krikler (bkrikler) wrote:**

I'm hoping that this has been fixed by merge request [gitlab:!15](https://gitlab.cern.ch/fast-hep/public/fast-carpenter/merge_requests/15).

**Comment by benkrikler** [comment]
**On 2018-11-27 Benjamin Krikler (bkrikler) wrote:**

I'm closing this off since I believe this has now been solved.

**Comment by benkrikler** [comment]
**On 2018-11-27 Benjamin Krikler (bkrikler) wrote:**

closed
